# Generated by Django 5.2.5 on 2026-01-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quiz_image_alter_quiz_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='', help_text='Правильна відповідь (тимчасово як текст)', max_length=255),
            preserve_default=False,
        ),
    ]
