# Generated by Django 5.2.5 on 2026-01-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quizsession_sessionplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizsession',
            old_name='is_active',
            new_name='started',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='created_at',
        ),
        migrations.AddField(
            model_name='quizsession',
            name='current_question',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
